baseurl = "https://nassilverbullet.github.io/"
languageCode = "ja"
title = "nas"
theme = "hugo-theme-yuki"
author = "nas"

# Copyright notice. This will display on the footer.
copyright = ""
paginate = 10

# Theme config
[params]

  # The content you want to be listed on list pages.
  mainSections = ["post"]

  # The information will display on the post pages.
  author = "nas"
  description = "Software engineer"
  authorwebsite = "https://nassilverbullet.github.io"

  # The path to your images
  favicon = "images/favicon.png"
  logo = "images/logo.png"
  displayImg = "images/display.png"

  # This will display on the index page
  snsTitle = "Social"

  # Google Analytics API key.
  ga_api_key = "UA-90317507-1"

  # TwitterID
  twitter = "nas_bullet"

# Navigation bar config
[[menu.nav]]
    name = "HOME"
    url = "/"
    weight = 1

[[menu.nav]]
    name = "BLOG"
    url = "/post"
    weight = 2

[[menu.nav]]
    name = "ABOUT"
    url = "/about"
    weight = 3

[[menu.nav]]
    name = "TAGS"
    url = "/tags/"
    weight = 4

# Social accounts config (This will display on the index page)
[[menu.social]]
    name = "GitHub"
    url = "https://github.com/nasjp"
    weight = 1

[[menu.social]]
    name = "Twitter"
    url = "https://twitter.com/nas_bullet"
    weight = 2
