version: 2
jobs:
  build:
    docker:
      # specify the version
      - image: circleci/golang:1.11

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    #### TEMPLATE_NOTE: go expects specific checkout path representing url
    #### expecting it in the form of
    ####   /go/src/github.com/circleci/go-tool
    ####   /go/src/bitbucket.org/circleci/go-tool
    working_directory: /go/src/github.com/NasSilverBullet/NasSilverBullet.github.io
    steps:
      - checkout
      - run:
          name: setup git
          command: |
              git config --global user.name "y.t."
              git config --global user.email "y.softvalley@gmail.com"
      - run:
          name: install hugo
          command: |
              go get github.com/gohugoio/hugo
              hugo version
      - run:
          name: push to master
          command: |
              hugo
              mkdir NasSilverBullet.github.io
              cp -rp .git NasSilverBullet.github.io
              cp -rp public/* NasSilverBullet.github.io
              cd NasSilverBullet.github.io
              git checkout -b master
              git add .
              git commit -m "[ci skip] publish"
              git push -f -u origin master
