name: CI
on:
  push:
    branches:
      - write

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: '0.63.1'

    - name: Check out code
      uses: actions/checkout@v1

    - name: Setup git
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config --global user.name "nas"
        git config --global user.email "nas.silver.bullet@gmail.com"
        git remote set-url origin https://NasSilverBullet:${GITHUB_TOKEN}@github.com/NasSilverBullet/NasSilverBullet.github.io.git

    - name: Push to master
      run: |
        hugo
        mkdir NasSilverBullet.github.io
        cp -rp .git NasSilverBullet.github.io
        cp -rp public/* NasSilverBullet.github.io
        cd NasSilverBullet.github.io
        git checkout -b master
        git add .
        git commit -m ":rocket:[ci skip] publish"
        git push -f -u origin master
