name: CI
on:
  push:
    branches:
      - write

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:

    - name: Check out code
    - uses: actions/checkout@v1
      with:
        submodules: true

    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: '0.63.1'

    - name: Push to master
      run: |
        hugo
        mkdir NasSilverBullet.github.io
        cp -rp .git NasSilverBullet.github.io
        cp -rp public/* NasSilverBullet.github.io
        cd NasSilverBullet.github.io
        git checkout -b master
        git add .
        git commit -m ":rocket:[ci skip] publish"
        git push -f -u origin master
